# -*- coding: utf-8 -*-
"""ITAI-1371-ML-LAb-MOD2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UKKWE2zr3zEszKfAC1G5efeRsIyBiZhe
"""

# Install required libraries (uncomment if needed)
# !pip install pandas
# Install numpy
# Install matplotlib
# Installmscikit-learn

# Import libraries with standard aliases
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt,
#"from sklearn import datasets"
# import warnings
# warnings.filterwarnings('ignore')
# Hide warning messages for cleaner output

print("Libraries installed successfully")
print("Pandas version: {pd_version_}")
print("Numpy version: {np_version_}")


# Load a simple dataset (Iris flowers - a classic beginner dataset),
"from sklearn.datasets import load_iris",

"#Load the data"
"iris = load_iris()"
print("Dataset loaded successfully!")
print('Dataset shape: {iris.data.shape}')
print('Features: {iris.feature_names}')
print('Target classes: {iris.target_names}')


# Create a simple scatter plot,
"plt.figure(figsize=(10, 6))",

#Plot sepal length vs sepal width, colored by species,
"species_colors = {'setosa': 'red', 'versicolor': 'blue', 'virginica': 'green'}",

"for species in df['species'].unique():",
"species_data = df[df['species'] == species]",
"plt.scatter(species_data['sepal length (cm)'])",
"species_data['sepal width (cm)']",
"c=species_colors[species]",
"label=species)",
"alpha=0.7",

"plt.xlabel('Sepal Length (cm)')",
"plt.ylabel('Sepal Width (cm)')",
"plt.title('Iris Dataset: Sepal Length vs Sepal Width')",
"plt.legend()",
"plt.grid(True, alpha=0.3)",
"plt.show()",

"print(\"\ud83c\udf89 Congratulations! You've created your first data visualization!)"


# Basic statistical analysis
"print(\"Basic Statistics for Iris Dataset:\)"
"print(\"=\" * 40)"

# Calculate mean values for each species\,
"species_means = df.groupby('species').mean()",
"print(\"\\Mean values by species:\")",
"print(species_means)",

# Count samples per species
"species_counts = df['species'].value_counts()",
"print(\"\\Samples per species:\")",
"print(species_counts)"